my_site_2/my_app_2/urls.py
from django.urls import path
from . import views


app_name = 'my_app_2'


urlpatterns = [
    path('', views.example_view, name='example'),
    path('variable/', views.variable_view, name='variable')
]

my_site_2/my_site_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app_2/', include('my_app_2.urls'))
]

handler404 = 'my_site_2.views.my_custom_page_not_found_view'

my_site_2/my_app_2/models.py
from django.db import models

# Create your models here.

my_site_2/my_app_2/views.py
from django.shortcuts import render


def example_view(request):
    # my_app_2/templates/my_app_2/example.html
    return render(request, 'my_app_2/example.html')


def variable_view(request):
    var = {'name': 'joe', 'surname': 'franklin', 'list': [1, 2, 3], 'user_logged_in': True}
    return render(request, 'my_app_2/variable.html', context=var)

my_site_2/my_site_2/views.py
from django.shortcuts import render


def my_custom_page_not_found_view(request, exception):
    return render(request, '404.html', status=404)

my_site_2/my_app_2/templates/my_app_2/example.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h2>This is inside example.html</h2>
<h2><a href="{% url 'my_app_2:variable' %}">To variable</a></h2>
<img src="{% static 'my_app_2/Python_logo.png'%}" alt="image">

{% endblock content %}

my_site_2/my_app_2/templates/my_app_2/variable.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Variable</h1>
    <h2>{{name | lower | capfirst}} {{surname | upper}}</h2>
    <ul>
        {% for item in list %}
            {% if item == 1 %}
                <li>ONE</li>
            {% else %}
                <li>{{item}}</li>
            {% endif %}
        {% endfor %}
    </ul>
    {% if user_logged_in %}
        <h2>You are logged in, {{name | lower | capfirst}}</h2>
    {% endif %}
    <h2><a href="{% url 'my_app_2:example' %}">To example</a></h2>
</body>
</html>

my_site_2/templates/base.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>base title</title>
</head>
<body>

<h1>This is above the BLOCK in base.html</h1>
{% block content %}

{% endblock content %}
<h1>This is above the BLOCK in base.html</h1>

</body>
</html>